In [3]:
import pandas as pd

In [4]:
data = {'Name':['Alice','Bob'],'Age':[25,30]}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
lst=[['Alice',25],['Bob',30]]
df=pd.DataFrame(lst,columns=['Name','Age'])
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [9]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [10]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [11]:
df['Age']

0    25
1    30
Name: Age, dtype: int64

In [12]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [13]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [14]:
df.loc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [15]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [17]:
df[df['Age']>20]

    Name  Age
0  Alice   25
1    Bob   30

In [21]:
df['Gender']=['F','M']

In [7]:
df = pd.DataFrame(data)
df['Age']=['30','25']

In [23]:
print(df)

    Name Gender
0  Alice      F
1    Bob      M

In [24]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [25]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [26]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [14]:
data={'department':['HR','IT','HR','IT','SALES'],'salary':[30000,50000,35000,60000,40000]}
df=pd.DataFrame(data)
res=df.groupby('department')['salary'].sum()
print(res)

department
HR        65000
IT       110000
SALES     40000
Name: salary, dtype: int64

In [15]:
data={'department':['HR','IT','HR','IT','SALES'],'salary':[30000,50000,35000,60000,40000]}
df=pd.DataFrame(data)
res=df.groupby('department')['salary'].mean()
print(res)

department
HR       32500.0
IT       55000.0
SALES    40000.0
Name: salary, dtype: float64

In [35]:
df1=pd.DataFrame({'id':[1,2,3],'name':['Alice','Bob','Charlie']})
df2=pd.DataFrame({'id':[1,2,4],'salary':[50000,60000,70000]})
res=pd.merge(df1,df2,on='id')
print(res)

   id   name  salary
0   1  Alice   50000
1   2    Bob   60000

In [21]:
df1=pd.DataFrame({'name':['Alice','Bob','Charlie']},index=[1,2,3])
df2=pd.DataFrame({'age':[25,30,35]},index=[1,2,3])
res=df1.join(df2)
print(res)

      name  age
1    Alice   25
2      Bob   30
3  Charlie   35

In [29]:
df=pd.read_csv('data.csv')

In [30]:
df.to_csv('output.csv',index=False)

In [37]:
print(df2.columns)

Index(['id', 'salary'], dtype='str')

In [39]:
df2.sort_values('salary')

   id  salary
0   1   50000
1   2   60000
2   4   70000

In [40]:
df2['salary'].apply(lambda x:x+1)

0    50001
1    60001
2    70001
Name: salary, dtype: int64

In [41]:
df2['id'].unique()

array([1, 2, 4])

In [ ]:
df2['salary'].value_counts()